### PR TITLE
feat: updated node to v20

### PR DESCRIPTION
**Pull request by BilalQamar95**
### Description

- Regenerated `package-lock.json` with node `v20` and NPM `10`.
- Updated `.nvmrc` to `v20`
- Updated the `lockfile` version check workflow

### CODE REVIEW

**Comment by justinhynes** [comment]
Pulled the branch and tried to do a bit of testing. Everything seemed to be working at this point and I think this should be safe to merge.

**Comment by justinhynes** [comment]
@BilalQamar95 I went to approve and merge this today but realized another PR I merged recently may have caused a conflict in the package-lock.

Any chance you could fix this up and i'll approve and merge it as a fast follow? Thanks in advance!

**Comment by BilalQamar95** [comment]
@justinhynes I have resolved conflicts & updated the PR

**Review by justinhynes — APPROVED** [review]

**Comment by MaxFrank13** [comment]
Part of #298

**Pull request merged**
