### PR TITLE
feat: updated frontend-build & frontend-platform major versions

### PR DESCRIPTION
**Pull request by BilalQamar95**
**Description**
Major version upgrades, Updating `frontend-build` to v14 & `frontend-platform` to v8 along with respective edx packages

### CODE REVIEW

**Comment by justinhynes** [comment]
Hi @BilalQamar95,

This is a draft PR that doesn't look like it has moved much lately. Is this still planned or required work? Can this be closed?

**Comment by BilalQamar95** [comment]
> Hi @BilalQamar95,
> 
> This is a draft PR that doesn't look like it has moved much lately. Is this still planned or required work? Can this be closed?

@justinhynes This is still planned from our side, some other PRs of ours are awaiting review, once they are merged dependency issues in this will be cleared out.

**Comment by justinhynes** [comment]
HI @BilalQamar95 -- it looks like you marked this as ready, but there are a couple of conflicts that need to be resolved in the package.json and package-lock.json files. Any chance you can fix this up and then I can get this on my radar this week while I'm on call?

**Comment by BilalQamar95** [comment]
> HI @BilalQamar95 -- it looks like you marked this as ready, but there are a couple of conflicts that need to be resolved in the package.json and package-lock.json files. Any chance you can fix this up and then I can get this on my radar this week while I'm on call?

@justinhynes I have resolved the conflicts

**Review by justinhynes — APPROVED** [review]

**Pull request merged**
