### PR TITLE
refactor: replace @edx/paragon and @edx/frontend-build

### PR DESCRIPTION
**Pull request by Mashal-m**
Part of https://github.com/openedx/axim-engineering/issues/23

This replaces the `@edx/paragon` and `@edx/frontend-build` package. 
Imports have been updated to use the same locations in the new package.

### CODE REVIEW

**Comment by justinhynes** [comment]
HI @Mashal-m, 

This doesn't look like it's had many changes in the past two weeks. Is this ready for review? Should this still be a draft PR?

**Comment by BilalQamar95** [comment]
Hi @justinhynes, this PR is now ready for review

**Comment by jsnwesson** [comment]
Since I had some time to look over this, I fixed a merge conflict that was going to be best handled by me. Everything else looked good in the original PR. I'll be merging and deploying next Tuesday!

**Review by jsnwesson — APPROVED** [review]

**Comment by deborahgu** [comment]
@Mashal-m  or @BilalQamar95 could you resolve the package.json  conflict again? I would do it myself but knowing what to choose out of the packages is the point of this PR and I'm not sure I would get it right.

**Pull request merged**
