### PR TITLE
chore(i18n): add more languages

### PR DESCRIPTION
**Pull request by Yoiber071**
Add Transifex Working Group languages.

New language codes: fr_CA,it_IT,pt_PT,de_DE,uk,ru,hi

@feanil 
@natabene

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Yoiber071!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by e0d** [comment]
@mphilbrick211 tests run.

**Comment by mphilbrick211** [comment]
Friendly ping on this @hurtstotouchfire :)

**Comment by mphilbrick211** [comment]
Hi @openedx/2u-aperture! Would someone be able to review/merge this? Thanks!

**Comment by jsnwesson** [comment]
Hi from Team Aperture, apologies about the delay! I'll be adding this to our kanban board to get this looked over!

**Comment by mphilbrick211** [comment]
> Hi from Team Aperture, apologies about the delay! I'll be adding this to our kanban board to get this looked over!

Hi @jsnwesson! Just checking in on this :)

**Review by jsnwesson — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@Yoiber071 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-learner-record&entry.867055334=https://github.com/openedx/frontend-app-learner-record/pull/139&entry.1484655318=https://github.com/Yoiber071&entry.752974735=2023-02-14+16:47&entry.1917517419=2023-07-19+06:09&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
