### PR TITLE
Renovate config to automate @edx namespaced minor/patch version upgrades

### PR DESCRIPTION
**Pull request by abdullahwaheed**
### Ticket
[Create common renovate config that automates @edx namespaced minor/patch version upgrades](https://github.com/openedx/frontend-wg/issues/116)

### What has changed
Added Renovate config to update and auto merge `@edx` name spaced minor and patch packages.
As no schedule is provided, it will create and merge renovate PRs at any time

### CODE REVIEW

**Review by MaxFrank13 — APPROVED** [review]

**Review by hurtstotouchfire — CHANGES_REQUESTED** [review]
@abdullahwaheed / @arbrandes Do we have a plan for situations like the Paragon 20 upgrade (with breaking changes) being hidden behind minor version upgrades of header / footer?

**Comment by arbrandes** [comment]
@hurtstotouchfire, good point.  However, such an upgrade should by definition be "major".  If one sneaks by as minor, it's basically a show stopper and should be fixed/reverted immediately.

**Comment by abdullahwaheed** [comment]
@hurtstotouchfire yes you are right, that should be major version change. We'll revisit all the MFEs with breaking changes and update the versioning accordingly. Let me create an issue for this as well

**Comment by arbrandes** [comment]
@abdullahwaheed, can you link to that issue you mention above?  Is there anything left to do here?

**Comment by abdullahwaheed** [comment]
@arbrandes i think @hurtstotouchfire can link the issue, I couldn't find it documented other than an old slack chat. For new changes, we are now maintaining breaking changes separately. I think its ok to merge as we have merged it elsewhere

**Pull request merged**
